title: Build a DAPP
description: Getting started with the Decentralized Internet SDK
template:
  repo: build-a-dapp-template
  name: build-a-dapp
  description: Build Decentralized Web and Distributed Computing Projects
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: Intro + Components
    description: The first step in your course
    event: issues.assigned
    link: 'https://github.com/Lonero-Team/build-a-dapp-template/blob/master/STEP1.md'
    actions:
      - type: closeIssue
  - title: Look at Clusterpost
    description: The first step in your course
    event: issues.assigned
    link: 'https://github.com/Lonero-Team/build-a-dapp-template/blob/master/STEP2.md'
    actions:
      - type: closeIssue
  - title: The GridBee Framework
    description: The first step in your course
    event: issues.assigned
    link: 'https://github.com/Lonero-Team/build-a-dapp-template/blob/master/STEP3.md'
    actions:
      - type: closeIssue
  - title: Looking at LNRChain
    description: The first step in your course
    event: issues.assigned
    link: 'https://github.com/Lonero-Team/build-a-dapp-template/blob/master/STEP4.md'
    actions:
      - type: closeIssue
  - title: Module 4 + Closing
    description: The first step in your course
    event: issues.assigned
    link: 'https://github.com/Lonero-Team/build-a-dapp-template/blob/master/STEP5.md'
    actions:
      - type: closeIssue
